name: Run Drip Script

on:
  schedule:
    - cron: "0 */8 * * *"  # Runs every 8 hours
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
        run: python drip_bot.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add claim_log.txt
          git commit -m "Update claim_log.txt"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
