name: Run Drip Script

on:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
        run: python drip_script.py
